vim.opt.number = true 
vim.opt.relativenumber = true
vim.opt.ignorecase = true
vim.opt.swapfile = false
-- indent options
vim.opt.smartindent = true
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
