vim.opt.number = true 
vim.opt.relativenumber = true
vim.opt.ignorecase = true
vim.opt.swapfile = false
vim.opt.clipboard = "unnamedplus"
-- indent options
vim.opt.smartindent = true
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
-- completion options
vim.opt.wildmode = "longest,list,full"
